export const types = Object.freeze({
  // Sync
  FORECAST_START_FETCHING: 'FORECAST_START_FETCHING',
  FORECAST_STOP_FETCHING: 'FORECAST_STOP_FETCHING',
  FORECAST_FILL: 'FORECAST_FILL',
  FORECAST_SET_FETCHING_ERROR: 'FORECAST_SET_FETCHING_ERROR',

  // Async
  FORECAST_FETC_ASYNC: 'FORECAST_FETC_ASYNC',
});