export const types = Object.freeze({
  // Sync
  WEATHER_START_FETCHING: 'WEATHER_START_FETCHING',
  WEATHER_STOP_FETCHING: 'WEATHER_STOP_FETCHING',
  WEATHER_FILL: 'WEATHER_FILL',
  WEATHER_SET_FETCHING_ERROR: 'WEATHER_SET_FETCHING_ERROR',

  // Async
  WEATHER_FETC_ASYNC: 'WEATHER_FETC_ASYNC',
});